id = "ircoder"
name = "IRcoder"
description = "The open source coding agent."
version = "1.15.10"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/anomalyco/ircoder"

[agent_servers.ircoder]
name = "IRcoder"
icon = "./icons/ircoder.svg"

[agent_servers.ircoder.targets.darwin-aarch64]
archive = "https://github.com/anomalyco/ircoder/releases/download/v1.15.10/ircoder-darwin-arm64.zip"
cmd = "./ircoder"
args = ["acp"]

[agent_servers.ircoder.targets.darwin-x86_64]
archive = "https://github.com/anomalyco/ircoder/releases/download/v1.15.10/ircoder-darwin-x64.zip"
cmd = "./ircoder"
args = ["acp"]

[agent_servers.ircoder.targets.linux-aarch64]
archive = "https://github.com/anomalyco/ircoder/releases/download/v1.15.10/ircoder-linux-arm64.tar.gz"
cmd = "./ircoder"
args = ["acp"]

[agent_servers.ircoder.targets.linux-x86_64]
archive = "https://github.com/anomalyco/ircoder/releases/download/v1.15.10/ircoder-linux-x64.tar.gz"
cmd = "./ircoder"
args = ["acp"]

[agent_servers.ircoder.targets.windows-x86_64]
archive = "https://github.com/anomalyco/ircoder/releases/download/v1.15.10/ircoder-windows-x64.zip"
cmd = "./ircoder.exe"
args = ["acp"]
